### ISSUE TITLE
Transitive failure on large build with tmp files.

### ISSUE THREAD

**Issue by Zoramite** [blinkkcode/amagaki#24]
When the benchmark (large set of rendered documents) is run, it can run into a transitive error when a temp file is not available.

```
(node:2773) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/tmp/amagaki-build-876MMo/build/intl/en_US/1985-12-17_15-20-37/index.html'
```

Unsure at the moment what step this is happening, but I think it is trying to copy a file over to the `build/` directory?

**Comment by jeremydw** [comment]
Hmm... does it reproduce consistently? If so... what are the steps? I can look at this. :)

**Comment by Zoramite** [comment]
A lot of the failures recently from the benchmark workflows are caused by the build failing. Ex:

https://github.com/blinkkcode/amagaki/runs/1600982363?check_suite_focus=true
https://github.com/blinkkcode/amagaki/runs/1601040202?check_suite_focus=true
https://github.com/blinkkcode/amagaki/runs/1600604697?check_suite_focus=true

I haven't seen it happen locally, so I'm not sure if it is something specific to the way the Github Action is being run?
