### ISSUE TITLE
Add built-in method for listing docs

### ISSUE THREAD

**Issue by jeremydw** [blinkkcode/amagaki#33]
Over the years we've had a few different ways to do this. We should standardize a canonical way.

```
// Docs are generated through a collection object.
1. pod.collection('pages').docs(options)
2. pod.collection('pages').listDocs(options)

// Docs are generated through the pod.
3. pod.docs('pages', options)
4. pod.listDocs('pages', options)
```

I have a slight preference for (3). Should we support both the syntax for (1) and (3), since there may be a use case for accessing a collection (e.g. its fields)?

**Comment by Zoramite** [comment]
- We are assuming that 'docs' are only things within `/content/` correct?
- It would be good to have a set of defined ways to filter that we can use across different parts of amagaki. For instance, in live-edit I use a [include/exclude filter](https://github.com/blinkkcode/live-edit/blob/main/src/utility/filter.test.ts) as the default way to interact with paths.
- I like the idea of supporting the doc listing on both the pod and individual collections. In code I would probably do that as the `collection.docs()` as a call to the `pod.docs()` with an extra filter.

Maybe `pod.docs(filters: string | Array<Filter>, options: ...)` where it can be used as just a simple text matching, or by providing an array of filters that get applied.

```
docs(filters: string | Array<Filter>, options: OptionsInterface) {
  docFilters: Array<Filter> = []
   if (isString(filters) {
    docFilters.push(new IncludeExcludeFilter({
      included: [filters],
    }
  } else {
     docFilters = filters
  }
  // ...
}
```

**Comment by jeremydw** [comment]
@Zoramite's suggestion looks good. Instead of a custom filter syntax I'm planning to send a PR that uses the glob module: https://www.npmjs.com/package/glob

I'm thinking glob syntax would be the most useful internally within Amagaki and for developers building out templates.
