### ISSUE TITLE
Add "root URL path" and "index" concepts

### ISSUE THREAD

**Issue by jeremydw** [blinkkcode/amagaki#49]
NOTE: Grow has a `podspec.root` concept but no "index" concept.

We need two concepts added in Amagaki:

1. The ability to specify a site-wide "root" or "mounting point" for projects. The requirement is that some projects need to build to an inner folder structure. Consider the following:

```
business.com -> site 1
business.com/foo/ -> site 2 (mounting point is "foo")
```

We need a way to reuse that "foo" across the project. In Grow, this was `podspec.root` but that term was very confusing with the `pod.root` (which is the root directory of the project on the filesystem).

To implement this, we can add a config option to `amagaki.js` that lets the developer specify the value, and then refer to it using `{{pod.config.mountPath}}` or similar. We just need to pick a name -- `mountPath`, `rootPath`, `root`, something else? My preference is `root` but I think that might be confusing with `pod.root` which is the filesystem path.

2. A shortcut to the "index" document for a collection. E.g.:

```
{{pod.collection('/content/docs').index}} -> Returns /content/docs/index.{SupportedExtension}
```

If we have both an `index.yaml` and `index.md` then the first one it encounters wins (although this would be a very uncommon occurrence). 

When building this out we should also have a "site-wide index", e.g. `{{pod.index}}` -- meaning the site's homepage. Or should we name this `{{pod.home}}` or something else?

**Comment by Zoramite** [comment]
What about `pod.basePath` for the mounting point of the urls?
