### ISSUE TITLE
Unable to install amagaki as an npm dependency

### ISSUE THREAD

**Issue by marchbox** [blinkkcode/amagaki#51]
I added this in my package.json’s `devDependencies` object:

```
"amagaki": "github:blinkkcode/amagaki#e09dc6eeea05414f4083d9ab55f1e002b8419ec2",
```

Then ran `npm i`, and got this error:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/zacky/Code/epos-storefront/node_modules/amagaki/src/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/zacky/Code/epos-storefront/node_modules/amagaki/src/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zacky/.npm/_logs/2021-04-07T00_19_51_517Z-debug.log
```

What's the current recommended way to use amagaki as a package?

**Comment by jeremydw** [comment]
Ah we actually publish Amagaki as a npm module `@amagaki/amagaki`.

That said, we recommend using the starter project as a starting point at this time. Our first pass on the Amagaki docs is about 75% done and has full instructions. I will share that with you as soon as it's ready.

Take a look at the starter for now. You can git clone it, npm install it, and run with it.
https://github.com/blinkkcode/amagaki-starter

**Comment by marchbox** [comment]
Ah cool! Thanks!
