### ISSUE TITLE
Benchmarks and continuous benchmarks

### ISSUE THREAD

**Issue by jeremydw** [blinkkcode/amagaki#6]
We want to ensure that as the project grows, memory usage and build times are kept in check.

We should investigate ways to benchmark these (i.e. by creating a benchmark project repository or generator, that can be used to benchmark builds) and add continuous benchmarking to a GitHub Action.

Relevant:  
https://github.com/rhysd/github-action-benchmark

**Comment by Zoramite** [comment]
Looking at the output that it uses for the `benchmarkjs` tests it looks like this:

```
fib(10) x 2,203,933 ops/sec ±0.16% (97 runs sampled)
fib(20) x 18,198 ops/sec ±0.12% (96 runs sampled)
```

We can add an output of our benchmark timing in that format and try using the benchmark action as part of our commits.
